name: ci-build
on: 
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-viz-ci-build.yml@main
      