name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master
  
# Cancels any release workflows in progress 
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-viz-release.yml@main
    # Inherits the Looker Automation Bot token to create release PRs and releases
    secrets: inherit